/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dongmodao_alpha_skill_skills_JNIUtils */

#ifndef _Included_com_dongmodao_alpha_skill_skills_JNIUtils
#define _Included_com_dongmodao_alpha_skill_skills_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dongmodao_alpha_skill_skills_JNIUtils
 * Method:    getRealStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dongmodao_alpha_skill_skills_JNIUtils_getRealStr
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
